var House = DS.Model.extend(
    {
        short_description: DS.attr('string'),
        description: DS.attr('string'),
        price: DS.attr('number'),
        location_url: DS.attr('string'),
        rooms: DS.attr('number'),
        floors: DS.attr('number'),
        bathrooms: DS.attr('number'),
        toilets: DS.attr('number'),
        kitchens: DS.attr('number'),
        garages: DS.attr('number'),
        images: DS.hasMany('Image', {async: true}),
        destination: DS.attr(),
        KI: DS.attr(),
        buildingPermit: DS.attr(),
        landDevelopment: DS.attr(),
        buildingViolation: DS.attr(),
        watertest: DS.attr(),
        epc: DS.attr(),
        epc_nr: DS.attr(),
        for_rent: DS.attr('boolean'),
        for_sale: DS.attr('boolean'),
        salesOption: DS.attr(),
        has_action: DS.attr('boolean'),
        action_text: DS.attr('string'),
        hasDocs: DS.attr('boolean'),
        documents: DS.hasMany('Document', {async: true})
    }
);


House.FIXTURES = [
    {
        id: 15,
        short_description: 'Verzorgde landelijke woning met veel mogelijkheden',
        description: '<p>Mooie, verzorgde woning met 3 slaapkamers, mogelijkheid tot vaste trap naar bovenverdieping en extra kamers te maken.</p><p>Ruime living met veel lichtinval met aansluitend de keuken en bureel of eventueel slaapkamer.</p><p>Grote berging en garage met elektrische garagepoort.</p><p>Al de deuren zijn voorzien van extra inbraakbeveiliging en de volledige woning is uitgerust met elektrische rolluiken, onder de woning is een kruipkelder, waar er gemakkelijk toegang is tot de leidingen.</p><p>Gezellige tuin met terras en tuinhuisje.</p><p>De woning is rolstoeltoegankelijk, in de ruime badkamer is een grote inloopdouche waar eventueel de mogelijkheid is om een bad te plaatsen.</p><p>Oprit autostrade (Scherpenheuvel-Zichem) op minder dan 5 km. Bushalte voor de deur en winkels, scholen, apotheek (Rillaar dorp) op ongeveer 3 km.</p><p>Mits kleine opfrissingswerken is dit een uniek pand en zeker een bezoekje waard voor starters.</p>',
        price: "Vanafprijs 230000,00 €",
        location_url: "<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2511.643609893245!2d4.910511599999998!3d50.985777800000015!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c1438ccdaee42d%3A0x467c05506d78e03d!2sMaasstraat+141%2C+3272+Scherpenheuvel-Zichem%2C+Belgium!5e0!3m2!1sen!2s!4v1433662140703\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\"></iframe>",
        rooms: 3,
        bathrooms: 1,
        toilets: 1,
        kitchens: 1,
        garages: 1,
        floors: 0,
        images: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
        destination: "woongebied",
        KI: "1.291 €",
        buildingPermit: "Ok",
        watertest: "Onroerend goed, niet gelegen in een overstromingsgebied",
        buildingViolation: "Nee",
        landDevelopment: "Nee",
        for_rent: false,
        for_sale: true,
        has_action: false,
        hasDocs: false,
        salesOption: "Nee",
        action_text: "Nieuw !!!!!",
        epc: " 449 kwh/m²",
        epc_nr: "20141113-0001700152-00000005-5",
        documents: []
    },
    {
        id: 16,
        short_description: 'Appartement te Aarschot',
        description: '<p>Appartement met twee slaapkamers op 250 meter van het station van Aarschot.</p><p>Dit gelijkvloers appartement is gelegen in het hartje van Aarschot, rustig gelegen in een straat met éénrichtingsverkeer. Achteraan een mooie veranda met een klein stukje groen.  Voldoende parkeergelegenheid in de buurt. </p><p>Ruime living met aansluitend de keuken en kleine berging met aansluiting voor wasmachine.</p><p>Badkamer met zitbad met de mogelijkheid om een ligbad te plaatsen.</p>',
        price: "180000,00 €",
        location_url: "<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2511.7235831977946!2d4.826266899999999!3d50.9842997!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c15cb1958d30ab%3A0x699410a4dcbb2876!2sFabriekstraat+33%2C+3200+Aarschot%2C+Belgium!5e0!3m2!1sen!2sus!4v1435263728203\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>",
        rooms: 1,
        bathrooms: 1,
        toilets: 1,
        kitchens: 1,
        garages: 0,
        floors: 0,
        images: [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        destination: "woongebied",
        KI: "725 €",
        buildingPermit: "Ok",
        watertest: "Onroerend goed, niet gelegen in een overstromingsgebied",
        buildingViolation: "Nee",
        landDevelopment: "Nee",
        for_rent: false,
        for_sale: true,
        has_action: false,
        hasDocs: false,
        salesOption: "Nee",
        action_text: "Nieuw !!!!!",
        epc: " 415 kwh/m²",
        epc_nr: "20150620-0001770160-1",
        documents: []
    },
    {
        id: 17,
        short_description: 'Mooie woning, landelijk en rustig gelegen en toch kort bij het centrum van Rillaar.',
        description: '<p>Indeling: alles gelegen op de gelijkvloers, maar de mogelijkheid is er om de bovenverdieping af te werken. Grote inkomhal met apart WC, grote living met veel lichtinval, keuken en 2 ruime slaapkamers. De ramen zijn voorzien van rolluiken.</p><p>De woning is volledig onderkelderd: grote garage, wasplaats en voldoende mogelijkheden voor het opbergen van materiaal.</p><p>Kortom indien u in een oase van rust wenst te wonen is dit de ideale woning, met vele uitbreidingsmogelijkheden.</p><p>De huidige eigenaars  zijn bereid de woning verder te huren indien deze verkocht wordt als opbrengsteneigendom. Indien dit niet het geval is en de koper de woning zelf zal bewonen zal de woning vrij zijn na het verlijden van de akte.</p>',
        price: "340000,00 €",
        location_url: "<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2512.0666308249147!2d4.907986!3d50.977959!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c1439343455329%3A0x92f9a98a40223c2e!2sLangestraat+42%2C+3202+Aarschot%2C+Belgium!5e0!3m2!1sen!2sus!4v1435299711377\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>",
        rooms: 2,
        bathrooms: 1,
        toilets: 1,
        kitchens: 1,
        garages: 1,
        floors: 0,
        images: [41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
        destination: "woongebied",
        KI: "899 €",
        buildingPermit: "Ok",
        watertest: "Onroerendgoed, niet gelegen in een overstromingsgebied",
        buildingViolation: "Nee",
        landDevelopment: "Nee",
        for_rent: false,
        for_sale: true,
        has_action: false,
        hasDocs: false,
        salesOption: "Nee",
        action_text: "Nieuw !!!!!",
        epc: " 714 kwh/m²",
        epc_nr: "20100221-0000452190-00000008-1",
        documents: []
    },
    {
        id: 18,
        short_description: '3 aanpalende woningen te Diest',
        description: '<p>De gebouwen zijn gelegen aan de zuidkant van de Veemarkt op een smalle strook tussen het Warandepark en de straatbedding van de Veemarkt.</p><p>Het gebouw Veemarkt nr 4 opgericht in 1950. Het gaat om een gesloten constructie met één verdieping en zolder. De voorgevelbreedte bedraagt 11,30 meter en de diepte varieert van 4,5 meter tot 6 meter. Achter dit gebouw bevindt zich een afgesloten tuin. Dit gebouw heeft een nuttige oppervlakte van 124m².</p><p>Het aanpalend gebouw Veemarkt nr 5, opgericht in 1842. Het ganse perceel is voorzien van een U-vormige constructie met centraal een niet-bebouwde en met klinkers verharde toegang tot de inkomhall. Het gaat om een halfopen constructie met één verdieping en een zolderverdieping.  Dit gedeelte paalt onmiddellijk aan het bovenvermelde gebouw Veemarkt nr 4.  Het heeft een gevelbreedte van 6,5 meter en een diepte van 15,40 meter.</p><p>Veemarkt 4 en 5 zijn opgenomen in een lijst van historisch, waardevolle gebouwen.</p><p>Het gebouw Veemarkt nr 6, opgericht in 1960. Het gaat om een halfopen constructie zonder verdieping en met een zolder. Ongeveer 1/3 van het gebouw is voorzien van een kelder.</p><p>De voorgevelbreedte bedraagt 28,15 meter en de diepte 9 meter. Het gebouw paalt achteraan quasi onmiddellijk aan het Warandepark. De inkom van het gebouw bevindt zich aan de linker-zijkant onder een klein afdak. Het gebouw heeft een bebouwde oppervlakte van 232 m² . Het bevindt zich op een quasi rechthoekig perceel met een totale breedte van ongeveer 30 meter en met een diepte van ongeveer 12 meter.</p>',
        price: "Vanafprijs 475000,00 €",
        location_url: "<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2511.6944962871485!2d5.054681599999999!3d50.984837299999995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c13f4cee449063%3A0x1a857c4c0931908!2sVeemarkt+4%2C+3290+Diest%2C+Belgium!5e0!3m2!1sen!2sus!4v1437807471855\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>",
        rooms: '-',
        bathrooms: '-',
        toilets: '-',
        kitchens: '-',
        garages: '-',
        floors: '-',
        images: [58, 59, 60, 61, 62, 63, 64, 65],
        destination: "Volgens Gewestplan Aarschot-Diest dd 7/11/1978 zijn de goederen gelegen in parkgebied.",
        KI: "-",
        buildingPermit: "Ok",
        watertest: "Overstromingsgevoelig gebied",
        buildingViolation: "Geen dagvaarding uitgebracht",
        landDevelopment: "Geen vergunning uitgereikt",
        for_rent: false,
        for_sale: true,
        has_action: false,
        hasDocs: false,
        salesOption: "Nee",
        action_text: "Nieuw !!!!!",
        epc: "",
        epc_nr: "",
        documents: []
    },
    {
        id: 19,
        short_description: "Vijf aaneengesloten woningen voor project te Lier ",
        description: '<p>Deze 5 aaneengesloten woningen (Kanaalstraat 53 t/m 61) lenen zich uitstekend tot één gezamenlijk nieuwbouwproject en zijn gelegen in een rustige straat aan de rand van Lier, vlakbij het centrum (1,5 km van de grote markt).</p><p>De woningen liggen in de groene rand aan de kruising van de Grote Nete en het Netekanaal en kijken uit op de vallei van de Grote Nete en een private grote vijver.</p><p>Mogelijks overstromingsgevoelig : heeft voornamelijk betrekking op het laatste stukje van bepaalde percelen.</p><p>Stedenbouwkundige voorschriften te verkrijgen op ons kantoor.</p>',
        price: "Vanafprijs: 318.000 €",
        location_url: "<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1789.0916130534815!2d4.589299100000299!3d51.13326689673044!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c3fc58f1cc0759%3A0x7da777a34fa58ae2!2sKanaalstraat+53%2C+2500+Lier%2C+Belgium!5e0!3m2!1sen!2sus!4v1437803782923\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>",
        rooms: '-',
        bathrooms: '-',
        toilets: '-',
        kitchens: '-',
        garages: '-',
        floors: '-',
        images: [55, 56, 57],
        destination: "woongebied",
        KI: "nr 53 € 304,00  / nr 55: € 352,00 / nr 57: € 364,00 / nr 59: € 473,00 / nr 61: € 314,00 - Totaal : € 1.807,00",
        buildingPermit: "Vergunning uitgereikt",
        watertest: "Mogelijk overstromingsgebied",
        buildingViolation: "Geen dagvaarding uitgebracht",
        landDevelopment: "Nee",
        for_rent: false,
        for_sale: true,
        has_action: false,
        hasDocs: false,
        salesOption: "Voorkooprecht voorhanden",
        action_text: "Nieuw !!!!!",
        epc: "",
        epc_nr: "",
        documents: []
    },
    {
        id: 20,
        short_description: "Te renoveren Herenhuis in het centrum van Diest",
        description: '<p>Deze mooie woning situeert zich vlak in het stadscentrum van Diest, op minder dan 100 meter afstand van het stadhuis en de Grote Markt, in de onmiddellijke nabijheid van scholen, handelszaken en openbare diensten en niet ver verwijderd van de verbindingen met het openbaar vervoer en de uitvalswegen van Diest.</p><p>De woning is rustig gelegen aan de voet van de Sint-Sulpitiuskerk  en is goed bereikbaar.</p><p>Het betreft een oud burgershuis-herenhuis  in gesloten bebouwing met twee verdiepingen en zolder onder een zadeldak.  De woning werd oorspronkelijk opgericht omstreeks 1824 en bevindt zich op een quasi rechthoekig perceel met een breedte van iets meer dan 12 meter en een diepte van ongeveer 30 meter.</p>',
        price: "325.000 € (verkocht per opbod)",
        location_url: "<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2511.675721694285!2d5.050845599999999!3d50.9851843!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c13f4d63fb29a1%3A0x1d4f8f601ec7eefb!2sCleynaertsstraat+12%2C+3290+Diest%2C+Belgium!5e0!3m2!1sen!2sus!4v1438105185984\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>",
        rooms: '-',
        bathrooms: '-',
        toilets: '-',
        kitchens: '-',
        garages: '-',
        floors: '-',
        images: [66, 67, 68, 69, 70, 71, 72, 73, 74],
        destination: " woongebied met een culturele, historische en of esthetische waarde",
        KI: " 892  €",
        buildingPermit: "Ja",
        watertest: "Geen overstromingsgevoelig gebied",
        buildingViolation: "Geen dagvaarding uitgebracht",
        landDevelopment: "Nee",
        for_rent: false,
        for_sale: true,
        has_action: false,
        hasDocs: false,
        salesOption: "Nee",
        action_text: "Nieuw !!!!!",
        epc: "",
        epc_nr: "",
        documents: []
    },
    {
        id: 21,
        short_description: "Vakantiewoning te koop te Langdorp in bosrijk gebied",
        description: '<p>Deze woning is volledig gemeubeld en uitgerust: meubilair, elektrische apparaten (koelkast, wasmachine, droogkast, etc), huishoudmateriaal (potten en pannen, beddengoed, handdoeken etc) inbegrepen.</p><p>Het terrein van 50 are is gelegen in een bosrijk gebied volledig omheind en is gelegen in een oase van rust, toegankelijk via een private weg. Er is eveneens een houtkachel aanwezig met een voorraad hout.</p><p>Momenteel verhuurd tot eind oktober 2015. Plaatsen van domicilie is niet mogelijk. Unieke kans voor starters!</p>',
        price: "115000 €",
        location_url: "<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2510.199447450223!2d4.880387!3d51.0124641!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c1448dd34dfc47%3A0x32b63f921199b4b0!2sKlein+Vleminkstraat+16%2C+3201+Aarschot%2C+Belgium!5e0!3m2!1sen!2sus!4v1438700755280\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>",
        rooms: '2',
        bathrooms: '1',
        toilets: '1',
        kitchens: '1',
        garages: '-',
        floors: '0',
        images: [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
        destination: "bosgebied",
        KI: "-",
        buildingPermit: "Ja",
        watertest: "Geen overstromingsgevoelig gebied",
        buildingViolation: "Geen dagvaarding uitgebracht",
        landDevelopment: "Nee",
        for_rent: true,
        for_sale: true,
        has_action: false,
        hasDocs: false,
        salesOption: "Nee",
        action_text: "Nieuw !!!!!",
        epc: "1669",
        epc_nr: "20120131-0001024396-00000007-5",
        documents: []
    },
    {
        id: 22,
        short_description: "Mooie te renoveren hoeve met tuin",
        description: '<p>Deze hoeve is zeer landelijk gelegen in een zijstraat van de grote baan van Beringen naar Diest. U zit in het midden van de natuur en toch kortbij een goede verbindingsbaan. Het achterliggende gebied is een gekend recreatiedomein voor fiets-en wandelliefhebbers.</p><p>Er zijn meerdere mogelijkheden met deze woning, u kan deze prachtig renoveren of afbraak en heropbouw is ook een mogelijkheid (=geen beschermd gebouw).</p><p>Mogelijkheid combinatie, gezinswoning en vrij beroep. Voldoende parkeermogelijkheid aan het gebouw. De totale oppervlakte van het terrein is 2020 m², de bewoonbare oppervlakte is ongeveer 350 m².</p><p>Het gebouw werd reeds volledig ontruimd en de eerste renovatiewerken werden gestart. Aarzel zeker niet om een bezoek te brengen aan dit prachtige pand.</p>',
        price: "249700,00 €",
        location_url: "<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2510.7288054756923!2d5.0917962000000125!3d51.0026834!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c138df627dc6e9%3A0xfe87dfb04273ddfe!2sKleinbergstraat+76%2C+3290+Diest%2C+Belgium!5e0!3m2!1sen!2sus!4v1441121096756\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>",
        rooms: 'nvt',
        bathrooms: 'nvt',
        toilets: 'nvt',
        kitchens: 'nvt',
        garages: 'nvt',
        floors: '0',
        images: [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103],
        destination: "woongebied",
        KI: "-",
        buildingPermit: "Ja",
        watertest: "Geen overstromingsgevoelig gebied",
        buildingViolation: "Geen dagvaarding uitgebracht",
        landDevelopment: "Nee",
        for_rent: true,
        for_sale: true,
        has_action: false,
        hasDocs: false,
        salesOption: "Nee",
        action_text: "Nieuw !!!!!",
        epc: "nvt",
        epc_nr: "nvt",
        documents: []
    }
];

export default
House;